### ISSUE TITLE
Popover button OnClick not working on 1.7.12

### ISSUE THREAD

**Issue by opti21** [tailwindlabs/headlessui#2337]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.7.12

**What browser are you using?**
Chrome

**Reproduction URL**

https://stackblitz.com/edit/next-typescript-vhbvzu?file=pages/index.tsx

**Describe your issue**
onClick doesn't exist on Popover.Button when it used to.
Get this error:

```
Type '{ children: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & CleanProps<"button", ButtonPropsWeControl> & OurProps<"button", ButtonRenderPropArg> & { ...; } & { ...; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & CleanProps<"button", ButtonPropsWeControl> & OurProps<"button", ButtonRenderPropArg> & { ...; } & { ...; }'.
```

**Comment by opti21** [comment]
Apologies this is fixed with the insiders install, looks like it's been worked on already. I'll look out for the next release :)
